# Generated by Django 4.1.5 on 2023-06-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_authenticated',
            field=models.BooleanField(null=True),
        ),
    ]
