# Generated by Django 4.1.5 on 2023-06-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0002_user_is_authenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_authenticated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
