# Generated by Django 4.1.5 on 2023-06-10 14:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0003_alter_user_is_authenticated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_enseignant', models.CharField(max_length=45)),
                ('prenom_enseignant', models.CharField(max_length=45)),
                ('image', models.BinaryField()),
                ('mail', models.CharField(max_length=45)),
                ('grade', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etudiant', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('password_etudiant', models.CharField(max_length=45)),
                ('image', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_examen', models.CharField(max_length=45)),
                ('start_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_groupe', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_module', models.CharField(max_length=45)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.examen')),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_salle', models.CharField(max_length=45)),
                ('capacite', models.IntegerField()),
                ('est_disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_section', models.CharField(max_length=45)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_authenticated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='adresse_mail',
            field=models.CharField(default='exemple@exemple.com', max_length=45),
        ),
        migrations.AddField(
            model_name='user',
            name='date_activation',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='user',
            name='date_expiration',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='user',
            name='login_user',
            field=models.CharField(default='default_value', max_length=45),
        ),
        migrations.AddField(
            model_name='user',
            name='nom_user',
            field=models.CharField(default='default_value', max_length=45),
        ),
        migrations.AddField(
            model_name='user',
            name='password_user',
            field=models.CharField(default='default_value', max_length=45),
        ),
        migrations.CreateModel(
            name='Surveillant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_surveillant', models.CharField(max_length=45, unique=True)),
                ('prenom_surveillant', models.CharField(max_length=45)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_presence', models.IntegerField()),
                ('marque_presence', models.BooleanField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.etudiant')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.groupe')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.module')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.salle')),
            ],
        ),
        migrations.AddField(
            model_name='groupe',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.salle'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.section'),
        ),
        migrations.AddField(
            model_name='examen',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.salle'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.section'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.user'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.user'),
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_admin', models.CharField(max_length=45)),
                ('prenom_admin', models.CharField(max_length=45)),
                ('login_admin', models.CharField(max_length=45)),
                ('password_admin', models.CharField(max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.user')),
            ],
        ),
    ]
