# Generated by Django 4.1.5 on 2023-06-10 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0004_enseignant_etudiant_examen_groupe_module_salle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='section',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='salle',
        ),
        migrations.RemoveField(
            model_name='groupe',
            name='salle',
        ),
        migrations.RemoveField(
            model_name='groupe',
            name='section',
        ),
        migrations.RemoveField(
            model_name='module',
            name='examen',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='groupe',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='module',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='salle',
        ),
        migrations.RemoveField(
            model_name='surveillant',
            name='enseignant',
        ),
        migrations.DeleteModel(
            name='Administrateur',
        ),
        migrations.DeleteModel(
            name='Enseignant',
        ),
        migrations.DeleteModel(
            name='Etudiant',
        ),
        migrations.DeleteModel(
            name='Examen',
        ),
        migrations.DeleteModel(
            name='Groupe',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Presence',
        ),
        migrations.DeleteModel(
            name='Salle',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Surveillant',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
