# Generated by Django 4.1.5 on 2023-06-11 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('useregistration', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='section',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='salle',
        ),
        migrations.RemoveField(
            model_name='groupe',
            name='salle',
        ),
        migrations.RemoveField(
            model_name='groupe',
            name='section',
        ),
        migrations.RemoveField(
            model_name='module',
            name='examen',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='groupe',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='module',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='salle',
        ),
        migrations.RemoveField(
            model_name='surveillant',
            name='enseignant',
        ),
        migrations.RemoveField(
            model_name='administrateur',
            name='login_admin',
        ),
        migrations.RemoveField(
            model_name='administrateur',
            name='password_admin',
        ),
        migrations.AddField(
            model_name='administrateur',
            name='id_user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrateur',
            name='image_admin',
            field=models.ImageField(default='k.jpeg', upload_to='image'),
        ),
        migrations.AddField(
            model_name='administrateur',
            name='location_admin',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='nom_admin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='prenom_admin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Enseignant',
        ),
        migrations.DeleteModel(
            name='Etudiant',
        ),
        migrations.DeleteModel(
            name='Examen',
        ),
        migrations.DeleteModel(
            name='Groupe',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Presence',
        ),
        migrations.DeleteModel(
            name='Salle',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Surveillant',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
