# Generated by Django 4.1.5 on 2023-06-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0007_remove_etudiant_section_remove_etudiant_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrateur',
            name='location_admin',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
