# Generated by Django 4.1.5 on 2023-06-11 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('useregistration', '0008_alter_administrateur_location_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('nom_etudiant', models.CharField(max_length=45)),
                ('prenom_etudiant', models.CharField(max_length=50)),
                ('image', models.BinaryField()),
                ('location_etudiant', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('nom_enseignant', models.CharField(max_length=50)),
                ('prenom_enseignant', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('grade', models.CharField(max_length=100)),
                ('location_enseignant', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
