# Generated by Django 4.1.5 on 2023-06-12 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0010_remove_enseignant_image_remove_etudiant_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='image_admin',
            new_name='image_etudiant',
        ),
    ]
