# Generated by Django 4.1.5 on 2023-06-15 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0012_alter_administrateur_user_alter_enseignant_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id_exam', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_examen', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('id_salle', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id_salle', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_salle', models.CharField(max_length=50)),
                ('capacite', models.IntegerField()),
                ('est_disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id_section', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_section', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Surveillant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_enseignant', models.IntegerField()),
                ('id_surveillant', models.IntegerField()),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.administrateur')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id_etudiant', models.IntegerField()),
                ('id_salle', models.IntegerField()),
                ('id_section', models.IntegerField()),
                ('id_exam', models.IntegerField()),
                ('id_presence', models.IntegerField(primary_key=True, serialize=False)),
                ('marque_presence', models.BooleanField(default=False)),
                ('date_de_presence', models.DateField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.etudiant')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.examen')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.salle')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.section')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id_module', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_module', models.CharField(max_length=50)),
                ('id_salle', models.IntegerField()),
                ('id_enseignant', models.IntegerField()),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.enseignant')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.salle')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_section', models.IntegerField()),
                ('id_etudiant', models.IntegerField()),
                ('id_salle', models.IntegerField()),
                ('nom_groupe', models.CharField(max_length=50)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.etudiant')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.salle')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.section')),
            ],
        ),
        migrations.AddField(
            model_name='examen',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.salle'),
        ),
    ]
