# Generated by Django 4.1.5 on 2023-06-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0013_examen_salle_section_surveillant_presence_module_and_more'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='administrateur',
    #         name='id',
    #     ),
    #     migrations.RemoveField(
    #         model_name='enseignant',
    #         name='id',
    #     ),
    #     migrations.RemoveField(
    #         model_name='etudiant',
    #         name='id',
    #     ),
    #     migrations.AlterField(
    #         model_name='administrateur',
    #         name='id_user',
    #         field=models.AutoField(primary_key=True, serialize=False),
    #     ),
    #     migrations.AlterField(
    #         model_name='enseignant',
    #         name='id_user',
    #         field=models.AutoField(primary_key=True, serialize=False),
    #     ),
    #     migrations.AlterField(
    #         model_name='etudiant',
    #         name='id_user',
    #         field=models.AutoField(primary_key=True, serialize=False),
    #     ),
    #]
