# Generated by Django 4.1.5 on 2023-06-15 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0015_alter_salle_id_salle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='id_salle',
        ),
        migrations.RemoveField(
            model_name='groupe',
            name='id_etudiant',
        ),
        migrations.RemoveField(
            model_name='groupe',
            name='id_salle',
        ),
        migrations.RemoveField(
            model_name='groupe',
            name='id_section',
        ),
        migrations.RemoveField(
            model_name='module',
            name='id_enseignant',
        ),
        migrations.RemoveField(
            model_name='module',
            name='id_salle',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='id_etudiant',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='id_exam',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='id_salle',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='id_section',
        ),
        migrations.RemoveField(
            model_name='surveillant',
            name='id_enseignant',
        ),
        migrations.AlterField(
            model_name='module',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useregistration.salle'),
        ),
        migrations.AlterField(
            model_name='salle',
            name='id_salle',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
