# Generated by Django 4.1.5 on 2023-06-17 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0017_remove_presence_etudiant_presence_etudiant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presence',
            old_name='exam',
            new_name='examen',
        ),
    ]
