# Generated by Django 4.1.5 on 2023-06-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0019_module_petit_nom_module_alter_module_enseignant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='petit_nom_module',
            field=models.CharField(default='', max_length=10),
        ),
    ]
