# Generated by Django 4.1.5 on 2023-06-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0020_alter_module_petit_nom_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='petit_nom_module',
            new_name='abreviation_nom_module',
        ),
    ]
