# Generated by Django 4.1.5 on 2023-06-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0021_rename_petit_nom_module_module_abreviation_nom_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='abreviation_nom_module',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
