# Generated by Django 4.1.5 on 2023-06-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0022_alter_module_abreviation_nom_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe',
            name='etudiant',
        ),
        migrations.AddField(
            model_name='groupe',
            name='etudiant',
            field=models.ManyToManyField(to='useregistration.etudiant'),
        ),
    ]
