# Generated by Django 4.1.5 on 2023-06-17 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0023_remove_groupe_etudiant_groupe_etudiant'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='groupe',
        #     name='etudiant',
        #     field=models.ManyToManyField(blank=True, null=True, to='useregistration.etudiant'),
        # ),
        migrations.AlterField(
            model_name='groupe',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useregistration.salle'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useregistration.section'),
        ),
    ]
