# Generated by Django 4.1.5 on 2023-06-17 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0025_remove_examen_nom_examen_remove_groupe_etudiant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='salle',
        ),
        migrations.AddField(
            model_name='groupe',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useregistration.section'),
        ),
    ]
