# Generated by Django 4.1.5 on 2023-06-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0026_remove_presence_salle_groupe_section'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='groupe',
        #     name='etudiant',
        #     field=models.ManyToManyField(blank=True, null=True, to='useregistration.etudiant'),
        # ),
    ]
