# Generated by Django 4.1.5 on 2023-06-20 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0028_rename_grade_enseignant_grade_enseignant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Presence',
        ),
    ]
