# Generated by Django 4.1.5 on 2023-06-20 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0029_delete_presence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id_presence', models.IntegerField(primary_key=True, serialize=False)),
                ('marque_presence', models.BooleanField(default=False)),
                ('date_de_presence', models.DateField()),
                ('etudiant', models.ManyToManyField(to='useregistration.etudiant')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.examen')),
            ],
        ),
    ]
