# Generated by Django 4.1.5 on 2023-06-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0031_presence_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Groupe',
        ),
    ]
