# Generated by Django 4.1.5 on 2023-06-20 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0032_delete_groupe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id_groupe', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_groupe', models.CharField(max_length=50)),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useregistration.salle')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useregistration.section')),
            ],
        ),
    ]
