# Generated by Django 4.1.5 on 2023-06-20 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0033_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='groupe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useregistration.groupe'),
        ),
    ]
