# Generated by Django 4.1.5 on 2023-06-21 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0037_groupe_enseignant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe',
            name='enseignant',
        ),
    ]
