# Generated by Django 4.1.5 on 2023-06-21 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0038_remove_groupe_enseignant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe',
            name='salle',
        ),
    ]
