# Generated by Django 4.1.5 on 2023-06-21 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0039_remove_groupe_salle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='enseignant',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useregistration.module'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useregistration.groupe'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useregistration.section'),
        ),
    ]
