# Generated by Django 4.1.5 on 2023-06-22 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0040_remove_module_enseignant_enseignant_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='groupe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='useregistration.groupe'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='section',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='useregistration.section'),
        ),
    ]
