# Generated by Django 4.1.5 on 2023-06-22 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0041_alter_etudiant_groupe_alter_etudiant_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='groupe',
            field=models.ForeignKey(blank=True, default='Groupe 1', on_delete=django.db.models.deletion.CASCADE, to='useregistration.groupe'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='section',
            field=models.ForeignKey(blank=True, default='Section 1', on_delete=django.db.models.deletion.CASCADE, to='useregistration.section'),
        ),
    ]
