# Generated by Django 4.1.5 on 2023-06-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0042_alter_etudiant_groupe_alter_etudiant_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='etudiant',
        ),
        migrations.DeleteModel(
            name='Etudiant',
        ),
    ]
