# Generated by Django 4.1.5 on 2023-06-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0044_etudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='etudiant',
            field=models.ManyToManyField(to='useregistration.etudiant'),
        ),
    ]
