# Generated by Django 4.1.5 on 2023-06-22 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0047_remove_enseignant_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useregistration.module'),
        ),
    ]
