# Generated by Django 4.1.5 on 2023-06-22 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0048_enseignant_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useregistration.module'),
        ),
    ]
