# Generated by Django 4.1.5 on 2023-06-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0050_remove_presence_date_de_presence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='date_examen',
        ),
    ]
