# Generated by Django 4.1.5 on 2023-06-22 13:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0051_remove_examen_date_examen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='module',
        ),
        migrations.AddField(
            model_name='examen',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='examen',
            name='enseignant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='useregistration.enseignant'),
        ),
    ]
