# Generated by Django 4.1.5 on 2023-06-22 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0052_remove_examen_module_examen_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.enseignant'),
        ),
    ]
