# Generated by Django 4.1.5 on 2023-06-22 13:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0054_remove_presence_examen_delete_examen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id_exam', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.enseignant')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useregistration.salle')),
            ],
        ),
        migrations.AddField(
            model_name='presence',
            name='examen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useregistration.examen'),
        ),
    ]
