# Generated by Django 4.1.5 on 2023-06-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0055_examen_presence_examen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='id_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
