# Generated by Django 4.1.5 on 2023-06-24 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0056_alter_etudiant_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useregistration.section'),
        ),
    ]
