# Generated by Django 4.1.5 on 2023-06-24 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0057_alter_etudiant_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='section',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='useregistration.section'),
        ),
    ]
