# Generated by Django 4.1.5 on 2023-06-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0058_alter_etudiant_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='id_section',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
