# Generated by Django 4.1.5 on 2023-06-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useregistration', '0059_alter_section_id_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='id_section',
            field=models.IntegerField(default=10, primary_key=True, serialize=False),
        ),
    ]
